# Generated by Django 2.1.7 on 2019-09-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0004_auto_20190727_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='availcarport',
            name='site_status',
            field=models.CharField(default='free', max_length=200),
        ),
    ]
