# Generated by Django 2.1.7 on 2019-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carport', '0005_availcarport_site_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availcarport',
            name='site_status',
            field=models.CharField(choices=[('free', '未被预约'), ('reserved', '已被预约')], default='free', max_length=200),
        ),
    ]
